### ISSUE TITLE
Android crossexample sample project build fail due to SDK import issues

### ISSUE THREAD

**Issue by trivedinikhil** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#134] opened 2016-06-16 10:47 UTC
local.properties : superpowered.dir is updated with location of `SuperpoweredSDK/Superpowered`, but still when try to build project getting error in `jni/HSuperpoweredExample.h`
ERROR
Error:(8, 45) SuperpoweredAdvancedAudioPlayer.h: No such file or directory
Information:(1) (Unknown) In file included

**Comment by superpoweredSDK** [comment] 2016-06-16 19:35
Perhaps there is a space or a special character in your path? Android Studio doesn't like it. Thousands of developers can successfully build, so i think the problem is very likely on your end.

**Comment by superpoweredSDK** [comment] 2016-06-18 15:14
Can i close this?

**Closed** 2016-06-21 07:16 UTC
