### ISSUE TITLE
SuperpoweredEcho result is wrong if number of samples > 1024

### ISSUE THREAD

**Issue by ksubox** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#122] opened 2016-05-26 09:02 UTC
I tested SuperpoweredEcho with Android. Original sound was 44100/stereo.
I processed echo by blocks of different number of samples and got result:
512 samples - OK
1024 samples - OK
1152 (usually MP3) - Wrong - spikes
2048 - Wrong - spikes

Is it intentional but non documented or just bug ?

**Comment by superpoweredSDK** [comment] 2016-05-26 12:51
Can't reproduce here unfortunately. Please show your code snippet creating and using the echo.

**Comment by ksubox** [comment] 2016-05-27 01:01
Below  is function I used:
```c++
static void produceEchoProblem(float mix, int samplesblock, const char *inname, const char *outname) {
	const char *fname = inname;
	const char *fname1 = outname;
	FILE *fr = fopen(fname,"rb");
	if (!fr) { return; }
	FILE *fw = fopen(fname1,"wb");
	if (!fw) { fclose(fr); return; }
	__android_log_print(ANDROID_LOG_DEBUG, "testnative", "produceEchoProblem start with %d blocksize", samplesblock);
	int16_t	intBuffer[8192];
	float		floatBuffer[8192];
	{
		SuperpoweredEcho filter(44100);
		filter.enable(true);
		filter.setMix(mix);
		while (true) {
			int samplesDecoded = fread(intBuffer, 4, samplesblock, fr);
			if (samplesDecoded < 1) break;
			SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
			bool res = filter.process(floatBuffer, floatBuffer, samplesDecoded);
			if (res) {
				SuperpoweredFloatToShortInt(floatBuffer, intBuffer, samplesDecoded);
				fwrite(intBuffer, 4, samplesDecoded, fw);
			}
		}
	}
	__android_log_print(ANDROID_LOG_DEBUG, "testnative", "produceEchoProblem completed");
	fclose(fr);
	fclose(fw);
}
```
I called like that:
```c++
produceEchoProblem(0.8f, 512, "/sdcard/rawaudio_orig_16.raw", "/sdcard/rawaudio_512.raw");
produceEchoProblem(0.8f, 1024, "/sdcard/rawaudio_orig_16.raw", "/sdcard/rawaudio_1024.raw");
produceEchoProblem(0.8f, 1152, "/sdcard/rawaudio_orig_16.raw", "/sdcard/rawaudio_1152.raw");
produceEchoProblem(0.8f, 2048, "/sdcard/rawaudio_orig_16.raw", "/sdcard/rawaudio_2048.raw");
```
Results you can download:
http://www.filedropper.com/rawaudio512
http://www.filedropper.com/rawaudio1024
http://www.filedropper.com/rawaudio1152
http://www.filedropper.com/rawaudio2048

And original file:
http://www.filedropper.com/rawaudioorig16

**Comment by superpoweredSDK** [comment] 2016-05-27 06:50
I found the problem. It's a bug. Will be fixed in the next release. Until then just please use 1024 samples or less.

**Closed by superpoweredSDK** 2016-05-27 06:50 UTC
