### ISSUE TITLE
Audio stuttering under CPU stress causes loss of sync

### ISSUE THREAD

**Issue by Guy-kun** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#112] opened 2016-04-16 12:13 UTC
I'm currently using the SDK to playback MP3s as background for a music game I'm developing. 
I simply use the AdvancedAudioPlayer to load and play() the mp3 files (which are bundled together with the apk on Android, hoping this gives the best playback performance.

I'm finding however that inconsistently, and more frequently when CPU usage is high due to something like screen recording, audio stutters. When this audio stutter happens it seems that synchronization is lost and playback falls behind the original intended speed/progress so the audio loses sync with what is on-screen.

My question is two things:
1) Is the stuttering under cpu strain usual? I've tested on a variety of fairly powerful devices and this seems to happen rarely (once per 2 plays of an mp3, or ~3-4 times if screen recording) across all of them
2) Is there any way that I can guarantee playback progress remains consistent even if this happens? I can see features related to synchronization but don't really know what's the best approach for this or if it is possible.

**Comment by superpoweredSDK** [comment] 2016-04-17 09:42
This is a duplicate of #113, i close it here and answer at #113.

**Closed by superpoweredSDK** 2016-04-17 09:42 UTC
